import "ITypeProvider.idl";

namespace SparsePackageManager.Pages
{
    [default_interface]
    runtimeclass PackageListPage : Windows.UI.Xaml.Controls.Page , SparsePackageManager.ITypeProvider
    {
        PackageListPage();
    }
}
