import "ITypeProvider.idl";

namespace SparsePackageManager.Pages
{
    [default_interface]
    runtimeclass RegisterPage : Windows.UI.Xaml.Controls.Page , SparsePackageManager.ITypeProvider
    {
        RegisterPage();
    }
}
