namespace SparsePackageManager
{
    [default_interface]
    runtimeclass RootContainer : Windows.UI.Xaml.Controls.Grid , Windows.UI.Xaml.Controls.INavigate
    {
        Boolean IsPaneOnTop{ get; set; };

        //Static Properties
        static RootContainer Current{ get; };

        static String AppName{ get; };
        static Windows.Foundation.Uri AppIcon { get; };
        static String Developer{ get; };
        static String Version{ get; };
    }
}
